source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftyDictionary_Example', :exclusive => true do
  pod "SwiftyDictionary", :path => "../"
end

target 'SwiftyDictionary_Tests', :exclusive => true do
  pod "SwiftyDictionary", :path => "../"

  
end
